with open("en/spotify-streams.html", "r", encoding="utf-8") as f:
    text = f.read()

replacements = {
    'lang="es"': 'lang="en"',
    'Promoción de Spotify Streams Reales': 'Real Spotify Streams Promotion',
    'Impulsa tu música en Spotify con campañas estratégicas. Streams 100% reales, entrega progresiva y retención que activa el algoritmo.': 'Boost your music on Spotify with strategic campaigns. 100% real streams, progressive delivery, and algorithm-activating retention.',
    '>Inicio<': '>Home<',
    '>Servicios<': '>Services<',
    '>Herramientas IA<': '>AI Tools<',
    '>Contacto<': '>Contact<',
    'Campañas Promocionales': 'Promotional Campaigns',
    'Impacta el algoritmo. Obtén streams reales con una estrategia de entrega natural diseñada para activar el Discover Weekly y Release Radar.': 'Impact the algorithm. Get real streams with a natural delivery strategy designed to trigger Discover Weekly and Release Radar.',
    'Impulsa tu': 'Boost Your',
    'Música': 'Music',
    'Crecimiento orgánico, retención real y activación algorítmica para artistas comprometidos.': 'Organic growth, real retention, and algorithmic activation for committed artists.',
    'Ventana Especial de Lanzamiento': 'Special Launch Window',
    'Durante esta fase promocional ofrecemos activación prioritaria para nuevas campañas.': 'During this promotional phase we offer priority activation for new campaigns.',
    'Días': 'Days',
    'Horas': 'Hours',
    'Min': 'Mins',
    'Seg': 'Secs',
    'Simulación de Crecimiento Progresivo': 'Progressive Growth Simulation',
    'Así es como estructuramos tu campaña para evitar penalizaciones y maximizar el <br>Discover Weekly y Release Radar.': 'This is how we structure your campaign to avoid penalties and maximize <br>Discover Weekly and Release Radar.',
    'Inicio Campaña': 'Campaign Start',
    'Indexación': 'Indexing',
    'Pico Orgánico': 'Organic Peak',
    'Día 1': 'Day 1',
    'Día 7': 'Day 7',
    'Día 14+': 'Day 14+',
    'campañas activas en las últimas 24 horas': 'active campaigns in the last 24 hours',
    'Paquetes Disponibles': 'Available Packages',
    'Elige el volumen de reproducciones que mejor se adapte a tu objetivo de retención y alcance.': 'Choose the stream volume that best suits your retention and reach goals.',
    'Streams reales de alta retención': 'High-retention real streams',
    'Entrega progresiva indetectable': 'Undetectable progressive delivery',
    'Aumento de oyentes mensuales': 'Monthly listener increase',
    'Protección algorítmica total': 'Full algorithmic protection',
    'Comprar Ahora': 'Buy Now',
    'MÁS POPULAR': 'MOST POPULAR',
    'Recomendado para lanzamientos': 'Recommended for releases',
    'Distribución Progresiva': 'Progressive Distribution',
    '100% Seguros para Algoritmo': '100% Algorithm Safe',
    'Retención Alta': 'High Retention',
    'Soporte Prioritario': 'Priority Support',
    'Entrega progresiva natural': 'Natural progressive delivery',
    'Aumento orgánico del Monthly Listeners': 'Organic Monthly Listener boost',
    'Escala de Autoridad': 'Authority Scaling',
    'Impacto algorítmico moderado-alto': 'Moderate-high algorithmic impact',
    'Ideal para activar Discover Weekly': 'Ideal for triggering Discover Weekly',
    'Distribución geográfica variada': 'Varied geographical distribution',
    'Posicionamiento de marca artista': 'Artist brand positioning',
    'Engagement sostenido': 'Sustained engagement',
    'Volumen avanzado de campaña': 'Advanced campaign volume',
    'Nivel de etiqueta independiente': 'Indie label level',
    'Impacto a lo largo de 45+ días': 'Impact over 45+ days',
    'Crecimiento exponencial de oyentes': 'Exponential listener growth',
    'Campaña nivel discográfica': 'Record label level campaign',
    'Distribución masiva progresiva': 'Massive progressive distribution',
    'Volumen Elite Chartable': 'Elite Chartable volume',
    'Prioridad Top-Tier': 'Top-Tier Priority',
    '¿Por qué esta estrategia es viable y segura?': 'Why is this strategy viable and safe?',
    'Transparencia y expectativas: cómo protegemos tu lanzamiento y aseguramos un crecimiento orgánico a largo plazo.': 'Transparency and expectations: how we protect your release and ensure long-term organic growth.',
    'Distribución Orgánica': 'Organic Distribution',
    'Nuestro sistema no utiliza bots de inyección rápida. Distribuimos tu canción a través de redes de usuarios reales que generan escuchas válidas, imitando a la perfección el comportamiento de descubrimiento humano.': 'Our system does not use fast-injection bots. We distribute your song through networks of real users generating valid streams, perfectly mimicking human discovery behavior.',
    'Seguridad de la Plataforma': 'Platform Safety',
    'Al adherirnos a una metodología de "goteo" lento, garantizamos la seguridad total de tu catálogo. Evitamos los picos masivos de streams artificiales que activan los sistemas antifraude y resultan en baneos.': 'By adhering to a slow "drip" methodology, we guarantee the total safety of your catalog. We avoid massive spikes of artificial streams that trigger anti-fraud systems and result in bans.',
    'Sin Tiempos Fijos': 'No Fixed Timelines',
    'La entrega progresiva significa que tu campaña tomará el tiempo necesario para parecer 100% natural. <strong>No prometemos resultados en 24 horas</strong>, prometemos resultados permanentes e indetectables.': 'Progressive delivery means your campaign will take the necessary time to look 100% natural. <strong>We do not promise results in 24 hours</strong>, we promise permanent and undetectable results.',
    '¿Para quién es esto?': 'Who is this for?',
    'Ideal para artistas comprometidos con construir autoridad. Si buscas inflar métricas rápidamente sin importar los riesgos, este servicio no es para ti. Diseñamos esto para carreras sostenibles.': 'Ideal for artists committed to building authority. If you are looking to inflate metrics quickly regardless of the risks, this service is not for you. We design this for sustainable careers.',
    'Información Importante de Nuestro Servicio': 'Important Information About Our Service',
    'Nuestras redes generan reproducciones a partir de <strong>usuarios 100% reales</strong>. No utilizamos bots.': 'Our networks generate plays from <strong>100% real users</strong>. We do not use bots.',
    'La entrega es <strong>gradual y natural</strong> (progresiva). Nunca enviamos todo el tráfico el mismo día.': 'Delivery is <strong>gradual and natural</strong> (progressive). We never send all traffic on the same day.',
    'Debido al goteo algorítmico seguro, <strong>no podemos garantizar una fecha exacta de finalización</strong> de la campaña.': 'Due to a safe algorithmic drip, <strong>we cannot guarantee an exact completion date</strong> for the campaign.',
    'Este modelo de crecimiento progresivo es lo único que <strong>protege la integridad de tu canción</strong> ante los filtros antifraude de Spotify.': 'This progressive growth model is the only thing that <strong>protects your song\'s integrity</strong> against Spotify\'s anti-fraud filters.',
    'La ventana promocional ha finalizado.': 'The promotional window has ended.',
    'Preguntas Frecuentes': 'Frequently Asked Questions',
    '¿Los streams son de cuentas reales?': 'Are the streams from real accounts?',
    'Sí. Utilizamos un red privada construida durante años que distribuye las escuchas de manera orgánica. No operamos granjas de servidores ni bots, lo que protege tu cuenta contra los recientes barridos de Spotify.': 'Yes. We use a private network built over years that distributes streams organically. We do not operate server farms or bots, which protects your account against recent Spotify sweeps.',
    '¿Cuánto tarda en entregarse el servicio?': 'How long does delivery take?',
    'Depende del paquete. Las entregas comienzan dentro de las 24-48h. Para paquetes desde 10k, la entrega se prolonga intencionalmente durante semanas para simular un crecimiento viral legítimo (progressive drip).': 'It depends on the package. Delivery starts within 24-48h. For packages from 10k, delivery is intentionally prolonged over weeks to simulate legitimate viral growth (progressive drip).',
    '¿Es seguro para mi cuenta de artista?': 'Is it safe for my artist account?',
    'Completamente. Spotify penaliza los picos abruptos (ej: recibir 10k streams en 1 hora). Nuestra metodología de goteo distribuye los plays basándose en la curva natural de escucha, haciéndolo indetectable para los algoritmos anti-fraude.': 'Completely. Spotify penalizes abrupt spikes (e.g., getting 10k streams in 1 hour). Our drip methodology distributes plays based on a natural listening curve, making it undetectable to anti-fraud algorithms.',
    '¿Me garantiza entrar en listas editoriales?': 'Does it guarantee editorial playlists?',
    'Ningún servicio externo legítimo puede garantizar listas editoriales, ya que esas decisiones las toman curadores humanos. Sin embargo, nuestros streams sí aumentan el ranking del algoritmo, lo que te posicionará para el Discover Weekly y Release Radar, el paso previo a la editorial.': 'No legitimate external service can guarantee editorial playlists, as those decisions are made by human curators. However, our streams do increase the algorithm ranking, positioning you for Discover Weekly and Release Radar, the step prior to editorial curation.',
    '¿Puedo cancelar o solicitar reembolso?': 'Can I cancel or request a refund?',
    'Dado que comenzamos a asignar los recursos en nuestra red inmediatamente después de la compra, no ofrecemos reembolsos una vez la campaña está activa, a menos que falláramos por completo en entregar el servicio descrito.': 'Since we begin allocating resources in our network immediately after purchase, we do not offer refunds once the campaign is active, unless we completely fail to deliver the described service.',
    '¿Puedo hacer Facebook/Instagram Ads al mismo tiempo?': 'Can I run Facebook/Instagram Ads at the same time?',
    'De hecho, lo alentamos. Combinar nuestro volumen algorítmico base con el tráfico súper cualificado de Facebook/Meta Ads es la estrategia utilizada por las discográficas modernas para construir super-fans mientras crecen los números absolutos.': 'In fact, we encourage it. Combining our base algorithmic volume with highly qualified traffic from Facebook/Meta Ads is the strategy used by modern record labels to build super-fans while growing absolute numbers.',
    'Nuestro Enfoque': 'Our Approach',
    'Artistas independientes utilizan esta estrategia como parte de su campaña de lanzamiento y visibilidad digital.': 'Independent artists use this strategy as part of their launch campaign and digital visibility.',
    'Asegura tu Campaña': 'Secure Your Campaign',
    'Descargo de Responsabilidad': 'Disclaimer',
    'Políticas de Privacidad': 'Privacy Policy',
    'Términos y Condiciones': 'Terms of Service',
    'Aviso de Afiliación': 'Affiliate Notice',
    'Derechos Reservados': 'All Rights Reserved',
    'Ingresa los detalles de tu lanzamiento para iniciar el impulso algorítmico.': 'Enter your release details to initiate the algorithmic push.',
    'Nombre Completo *': 'Full Name *',
    'Correo Electrónico *': 'Email Address *',
    'Nombre del Artista *': 'Artist Name *',
    'Enlace de la Canción (Spotify) *': 'Spotify Song Link *',
    'Paquete Seleccionado:': 'Selected Package:',
    'Notas Opcionales (ej., género musical, demografía)': 'Optional Notes (e.g., genre, demographics)',
    'Entiendo que la entrega es progresiva y no se garantiza una fecha exacta de finalización.': 'I understand that delivery is progressive and an exact completion date is not guaranteed.',
    'Proceder al Pago': 'Proceed to Payment'
}

for k, v in replacements.items():
    text = text.replace(k, v)

with open("en/spotify-streams.html", "w", encoding="utf-8") as f:
    f.write(text)
